version: '3.4'
services:
  linuxgsm${id}:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gmodserver${id}
    environment:
      - GAMESERVER=gmodserver
      - LGSM_GITHUBUSER=GameServerManagers
      - LGSM_GITHUBREPO=LinuxGSM
      - LGSM_GITHUBBRANCH=master
    volumes:
      - /home/gmodserver/gmodserver-docker/serverfiles:/home/linuxgsm/serverfiles
      - /home/gmodserver/gmodserver-docker/log:/home/linuxgsm/log
      - /home/gmodserver/gmodserver-docker/config-lgsm:/home/linuxgsm/lgsm/config-lgsm
    ports:
      - "${sv_port}:${sv_port}/tcp"
      - "${sv_port}:${sv_port}/udp"
      - "${port}:${port}/udp"
      - "${cl_port}:${cl_port}/udp"
    restart: unless-stopped
