name: Run ltservers docker api

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v1
      - name: Docker Build
        run: docker build -t pjgame841/ltservers-api .
      - name: Stop old containers
        run: docker rm $(docker stop $(docker ps -a -q --filter name=pj_ltservers_api --format="{{.ID}}"))
        continue-on-error: true
      - name: Remove old image
        run: docker rmi -f $(docker images -f "dangling=true" -q)
        continue-on-error: true
      - name: Start
        env:
          API_KEY: '${{ secrets.API_KEY }}'
          RCONPASSWORD: '${{ secrets.RCONPASSWORD }}'
        run: docker run -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock --network gmodnetwork --env API_KEY=$API_KEY --env RCONPASSWORD=$RCONPASSWORD -d --name=pj_ltservers_api pjgame841/ltservers-api